package telran.accounting.api;

public enum AccountingCodes {
OK, ACCOUNT_ALREADY_EXISTS,
ACCOUNT_NOT_EXISTS,ACCOUNT_REVOKED,
WRONG_PASSWORD,ACCOUNT_ACTIVATED,
ROLE_ALREDY_EXISTS, ROLE_NOT_EXISTS,
SAME_PASSWORD, PASSWORD_ALREADY_USED
}
